# Generated by Django 3.2.13 on 2022-05-15 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=25)),
                ('cpf', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('turma', models.IntegerField(choices=[('A', 101), ('B', 201), ('C', 301), ('D', 401), ('E', 501), ('F', 601)])),
            ],
        ),
    ]
