# Generated by Django 3.2.13 on 2022-05-15 14:52

import cpf_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='foto',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AlterField(
            model_name='student',
            name='cpf',
            field=cpf_field.models.CPFField(max_length=14, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='nome',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='student',
            name='turma',
            field=models.IntegerField(choices=[(101, 101), (201, 201), (301, 301), (401, 401), (501, 501), (601, 601)]),
        ),
    ]
