# Generated by Django 3.2.13 on 2022-05-15 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20220515_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='foto',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
